version: '3.8'

services:
  mongodb:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: muhabdulloh/tracking_number_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tracking_number_db?maxPoolSize=20&minPoolSize=5
    depends_on:
      - mongodb

volumes:
  mongo_data: